### ISSUE TITLE
symlink error

### ISSUE THREAD

**Issue by mhwasil** [b-it-bots/mas_perception#23]
I got this error after pulling new changes from github. @minhnh have you ever faced this? I did catkin clean already, but it did not solve the error.
@sthoduka 
```______________________________________________________________________________________________________________________
Errors     << mcr_scene_segmentation:symlink /home/robocup/ros/robocup/logs/mcr_scene_segmentation/build.symlink.000.log
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/stages.py", line 174, in function_proxy
    return function(logger, event_queue, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/jobs/catkin.py", line 291, in link_devel_products
    source_hash = md5(open(os.path.realpath(source_file)).read().encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 40: ordinal not in range(128)

Stage `symlink` failed with arguments:
  package: {'buildtool_export_depends': [], 'test_depends': [<catkin_pkg.package.Dependency object at 0x7f4802dc9130>], 'exec_depends': [<catkin_pkg.package.Dependency object at 0x7f4802dc91a0>, <catkin_pkg.package.Dependency object at 0x7f4802dc9210>], 'build_depends': [<catkin_pkg.package.Dependency object at 0x7f4802dc9280>, <catkin_pkg.package.Dependency object at 0x7f4802dc92f0>, <catkin_pkg.package.Dependency object at 0x7f4802dc9360>, <catkin_pkg.package.Dependency object at 0x7f4802dc93d0>, <catkin_pkg.package.Dependency object at 0x7f4802dc9440>, <catkin_pkg.package.Dependency object at 0x7f4802dc94b0>, <catkin_pkg.package.Dependency object at 0x7f4802dc9520>, <catkin_pkg.package.Dependency object at 0x7f4802dc9590>, <catkin_pkg.package.Dependency object at 0x7f4802dc9600>, <catkin_pkg.package.Dependency object at 0x7f4802dc9670>, <catkin_pkg.package.Dependency object at 0x7f4802dc96e0>], 'licenses': ['GPLv3'], 'group_depends': [], 'doc_depends': [], 'filename': '/home/robocup/ros/robocup/src/mas_perception/mcr_scene_segmentation/package.xml', 'version': '0.0.1', 'package_format': 1, 'exports': [], 'description': u'Scene segmentation', 'build_export_depends': [<catkin_pkg.package.Dependency object at 0x7f4802dc9750>, <catkin_pkg.package.Dependency object at 0x7f4802dc97c0>], 'maintainers': [<catkin_pkg.package.Person object at 0x7f4802dc3f90>], 'member_of_groups': [], 'authors': [<catkin_pkg.package.Person object at 0x7f4802dcf050>, <catkin_pkg.package.Person object at 0x7f4802dcf0d0>, <catkin_pkg.package.Person object at 0x7f4802dcf150>], 'conflicts': [], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0x7f4802dc9830>], 'version_compatibility': None, 'replaces': [], 'name': 'mcr_scene_segmentation', 'urls': []}
  metadata_path: /home/robocup/ros/robocup/.catkin_tools/profiles/default
  devel_manifest_path: /home/robocup/ros/robocup/.catkin_tools/profiles/default/packages/mcr_scene_segmentation
  prebuild: False
  package_path: mas_perception/mcr_scene_segmentation
  dest_devel_path: /home/robocup/ros/robocup/devel
  source_devel_path: /home/robocup/ros/robocup/devel/.private/mcr_scene_segmentation
......................................................................................................................
Failed     << mcr_scene_segmentation:symlink                      [ Exited with code 3 ]    
```

**Comment by alex-mitrevski** [comment]
I currently have a CATKIN_IGNORE in `mcr_scene_segmentation` because of this exact same error.

**Comment by argenos** [comment]
I have a feeling I also had this error at some point. Have you tried adding this to the file in question:


```python
import sys
reload(sys)
sys.setdefaultencoding(‘utf8’)
```

Found my error, see comment below.

**Comment by argenos** [comment]
It seems it’s an issue of catkin-tools: https://github.com/catkin/catkin_tools/issues/500

**Comment by sthoduka** [comment]
Possible solution:
Delete the following folders:
```
devel/lib/<package name>
devel/.private/<package name>
devel/lib/python2.7/<package name>
devel/share/<package name>
build/<package name>
```

```
export LC_CTYPE=en_US.UTF-8
```
build again
